(package "blade-ts-mode"
         "0.0.1"
         "Tree-sitter based major mode for Blade template files")

(website-url "https://github.com/FunctorFactory/blade-ts-mode")
(keywords "languages" "php" "tree-sitter" "blade" "web")

(package-file "blade-ts-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.0")
(depends-on "web-mode")
